version: '3'

services:

  spring-redis-api:
    image: habeebcycle/spring-redis-api:v1
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    depends_on:
      - redis

  # $ redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"